version: 2.1

orbs:
  android: circleci/android@3.1.0

jobs:
  build-library:
    executor:
      name: android/android_machine
      resource_class: large
      tag: 2024.11.1
    steps:
      - checkout
      - run:
          name: Build and test library
          command: ./gradlew clean assemble test

  deploy-to-sonatype:
    executor:
      name: android/android_machine
      resource_class: large
      tag: 2024.11.1
    steps:
      - checkout
      - run:
          name: Define LIBRARY_VERSION Environment Variable at Runtime
          command: |
            if [ $CIRCLE_TAG ]
              then
                echo 'export LIBRARY_VERSION=$CIRCLE_TAG' >> $BASH_ENV
              else
                echo "export LIBRARY_VERSION=`git tag | tail -1`-SNAPSHOT" >> $BASH_ENV
            fi
            source $BASH_ENV
      - run:
          name: Build library
          command: ./gradlew assemble
      - run:
          name: Build and publish
          command: ./gradlew jreleaserConfig build publish
      - run:
          name: Release
          command: ./gradlew jreleaserFullRelease
      - store_artifacts:
          path: android-library-example/build/jreleaser/trace.log
          destination: jreleaser-trace.log
          when: always

parameters:
  run-schedule:
    type: boolean
    default: false

workflows:
  build-test-deploy:
    when:
      not: << pipeline.parameters.run-schedule >>
    jobs:
      - build-library:
          name: build-and-test
          filters:
            tags:
              only: /^[0-9]+.*/
      - hold-for-approval:
          type: approval
          requires:
            - build-and-test
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
      - deploy-to-sonatype:
          name: Deploy to Maven Central
          requires:
            - hold-for-approval
          filters:
            tags:
              only: /^[0-9]+.*/

  nightly-snapshot:
    when: << pipeline.parameters.run-schedule >>
    jobs:
      - build-library:
          name: build-and-test
      - deploy-to-sonatype:
          name: Deploy Snapshot to Sonatype
          requires:
            - build-and-test
