[versions]
kotlin = "2.1.0"
android-gradle = "8.8.0" # https://developer.android.com/studio/releases/gradle-plugin
junit = "5.11.4"
festassert = "2.0M10"
festandroid = "1.0.8"
robolectric = "4.14.1"
jreleaser = "1.19.0"

[libraries]
junit = { group = "org.junit.vintage", name = "junit-vintage-engine", version.ref = "junit" }
festassert = { group = "org.easytesting", name = "fest-assert-core", version.ref = "festassert" }
festandroid = { group = "com.squareup", name = "fest-android", version.ref = "festandroid" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

[bundles]

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }